application: cloud-dj
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: dataServer.app

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
