application: cloud-dj
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /soundmanager
  static_dir: js/soundmanagerv297a-20121104

- url: /js
  static_dir: js

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images

- url: /.*
  script: masterServer.app

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

inbound_services:
- channel_presence
